### ISSUE TITLE
Non-ASCII character '\xe2' in configurator

### ISSUE THREAD

**Issue by davidedelvento** [UV-CDAT/uvcdat#1936]
```
File "uv_cdat/lib/python2.7/site-packages/vcs/configurator.py", line 126
SyntaxError: Non-ASCII character '\xe2' in file uv_cdat/lib/python2.7/site-packages/vcs/configurator.py on line 126, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details
urator.py on line 126, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details
```
Easy to remove the offending character from https://github.com/UV-CDAT/uvcdat/blob/master/Packages/vcs/vcs/configurator.py#L125 (the one after uvcdat), but pretty annoying

**Comment by doutriaux1** [comment]
i believe this has been fixed already

**Comment by davidedelvento** [comment]
@doutriaux1 -- I believe?? Can't you check the link that I conveniently added to the report and see that the problem is still there? I'm appalled.

**Comment by davidedelvento** [comment]
Again, upon closer examination, you are correct. I was misguided into my previous comment by:
1) your use of "I believe" which sounded to me as not 100% sure
2) the fact that the offending character has not been deleted, but replaced by a dash (i.e. "-") which looked similar on the web compared to \xe2 in my editor

I apologize for having being harsh

**Comment by doutriaux1** [comment]
no worries. it shows you care.
