### ISSUE TITLE
Tests are failing on master branch as of May 31st on some systems

### ISSUE THREAD

**Issue by aashish24** [UV-CDAT/uvcdat#1995]

**Comment by aashish24** [comment]
@danlipsa i believe for the stipple one, it reported that baseline was missing. I can run the test again to post full information.

**Comment by aashish24** [comment]
@doutriaux1 both me and @danlipsa had tests failing on master branch as of May 31st. Could you please confirm if thats the case on your system as well (checkout master as of May 31st please). 

Below is the list of tests that were failing for me on master before we merged vector branch. 
354 - test_vcs_isoline_width_stipple (Failed)
452 - test_vcs_line_patterns (Failed)
523 - dv3d_vector_test (Failed)
524 - dv3d_slider_test (Failed)
525 - Hovmoller_volume_test (Failed)
526 - dv3d_volume_test (Failed)
527 - dv3d_constituents_test (Failed)
528 - dv3d_surface_test (Failed)
529 - dv3d_hovmoller_test (Failed)
575 - CDMS_Test_multiple_formats (Failed)
587 - diags_test_02 (Failed)
588 - diags_test_03 (Failed)
589 - diags_test_04 (Failed)
590 - diags_test_41 (Failed)
591 - diags_test_05 (Failed)
592 - diags_test_06 (Failed)
593 - diags_test_07 (Failed)
594 - diags_test_08 (Failed)
595 - diags_test_09 (Failed)
596 - diags_test_10 (Failed)
597 - diags_test_11 (Failed)
598 - diags_test_12 (Failed)
599 - diags_test_13 (Failed)
600 - diags_test_15 (Failed)

**Comment by danlipsa** [comment]
@aashish24 I fixed
354 - test_vcs_isoline_width_stipple (Failed)
452 - test_vcs_line_patterns (Failed)
Those pass on master now.

**Comment by aashish24** [comment]
thanks @danlipsa. I believe the diags tests are still failing for you?
